- hosts: web
  tasks:
  - name: Setting up yum for docker
    yum_repository:
            name: "docker-ce"
            description: "docker yum configure"
            baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
            gpgcheck: no
            state: present

  - name : installing docker
    package:
            name: "docker-ce-18.06.3.ce-3el7"
            state: latest 

  - name: installing httpd          
    package: 
           name: "httpd"
           state: present


  - name: start docker service
    service:
            name: "docker"
            state: started
            enabled: yes
          
  - pip:
            name: "docker"
            state: present

  - pip:
            name: "urllib3"
            state: present

  - name: docker image
    docker_image:
            name: "httpd:latest"

  - name: docker container configuring
    docker_container:
            name:  "webserver_ansible"
            image: httpd:latest
            state: started
            detach: yes
            ports: "8081:80"
            volumes: /var/www/html:/usr/local/apache2/htdocs/

  - name: copying web page
    copy:
            content: "<h1><center>  Ansible Integration with docker </center> </h1>"
            dest: "/var/www/html/index.html"

  - name: starting httpd service          
    service:
          name: "httpd"
          state: started
          enabled: yes

  - name: setting up firewall to expose it to public        
    firewalld:
          port: "80/tcp"
          state: enabled
          permanent: yes
          immediate: yes
